rules:
  anonymous-definition:
    disable: true
  concurrency-limits:
    disable: true
  dependabot-cooldown:
    disable: true
  if-cond:
    disable: true
  undocumented-permissions:
    disable: true
